# Generated by Django 5.2.1 on 2025-06-19 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('annotation', models.TextField()),
                ('title_image', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('last_book', models.BooleanField(default=False)),
                ('facultet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.facultet')),
            ],
        ),
    ]
