# Generated by Django 5.2.1 on 2025-06-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
