# Generated by Django 5.2.1 on 2025-06-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_book_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mobile_folder',
            field=models.FilePathField(allow_folders=True, blank=True, null=True, path='media/books', recursive=True, verbose_name='Папка с мобильной версией'),
        ),
    ]
