# Generated by Django 5.2.1 on 2025-06-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_book_mobile_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='mobile_folder',
        ),
        migrations.AddField(
            model_name='book',
            name='mobile_zip',
            field=models.FileField(blank=True, null=True, upload_to='books/zips/', verbose_name='ZIP-файл с мобильной версией'),
        ),
    ]
