# Generated by Django 5.2.1 on 2025-06-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_book_mobile_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='specialty_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
