# Generated by Django 5.2.4 on 2025-10-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_book_specialty_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='mobile_folder',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Папка с HTML книгой'),
        ),
        migrations.AlterField(
            model_name='book',
            name='mobile_zip',
            field=models.FileField(blank=True, null=True, upload_to='books/zips/', verbose_name='ZIP-файл книги'),
        ),
    ]
