# Generated by Django 5.0.4 on 2026-01-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_book_mobile_folder_alter_book_mobile_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('video_file', models.FileField(upload_to='video_lectures/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
